version: '3'
services:
  emddesafio:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: ["python", "main.py"]  
    restart: always
    tty: "true"